{{- if .Values.runner.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-runner
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-runner
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: runner
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  {{- if .Values.runner.hmacKey }}
  RUNNER_HMAC_KEY: {{ .Values.runner.hmacKey | b64enc }}
  {{- else }}
  RUNNER_HMAC_KEY: {{ randAlphaNum 64 | b64enc }}
  {{- end }}
{{- end }}
